version: '3.8'

services:

  airflow:
    build: .
    image: airflow
    container_name: airflow
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FLASK_DEBUG=1

  provider_a:
    build: ./provider_a
    ports:
      - "9001:9001"

  provider_b:
    build: ./provider_b
    ports:
      - "9002:9002"